### ISSUE TITLE
400 error from morpheus_environment example

### ISSUE THREAD

**Issue by bevel-zgates** [gomorpheus/terraform-provider-morpheus#143]
```
resource "morpheus_environment" "sample" {
  active      = true
  code        = "staging"
  description = "Staging"
  name        = "Staging"
}
```
Response:
```
│ Error: API returned HTTP 400
│
│   with morpheus_environment.sample,
│   on cloud.tf line 22, in resource "morpheus_environment" "sample":
│   22: resource "morpheus_environment" "sample" {
│
```
```
provider "registry.terraform.io/gomorpheus/morpheus" {
  version     = "0.9.3"
```
Morpheus version 6.1.2

**Comment by martezr** [comment]
This error is being thrown because an environment with the same code attribute already exists. The code example in the documentation is being updated to provide an example that doesn't already exist out of the box and work is being done to more clearly display the full error message returned from the API.
