### ISSUE TITLE
morpheus_instance_catalog_item : option_type_ids

### ISSUE THREAD

**Issue by jigeay** [gomorpheus/terraform-provider-morpheus#148]
Hello, 
Seems [option_type_ids](https://registry.terraform.io/providers/gomorpheus/morpheus/latest/docs/resources/instance_catalog_item#option_type_ids) takes a list of option types ids, but it doesn't work : 
when i use the id of the created objects in terraform, like this : 
```
resource "morpheus_instance_catalog_item" "vmcreation_vsphere" {
  config          = file("data/vmcreation_vsphere-config.json")
  content         = "Windows Catalog Item :"
  description     = "A catalog item used to deploy a virtual machine on a BEL environment"
  enabled         = true
  featured        = true
#   image_name      = null
#   image_path      = "windows.svg"
  labels                   = ["vmcreation", "terraform_managed"]
  name            = "Windows 2k19 Office on vmware"
  option_type_ids = [morpheus_api_option_list.networks.id, morpheus_manual_option_list.technicalServices.id, morpheus_api_option_list.clouds.id]
  visibility      = "public"
}
```
option_type_ids are [6,7,10], which are the real ids of the option list (in the uri)

I have no option appearing in the UI.
I tried to import an already existing catalog into terraform, and it gives me that code ;
```
 resource "morpheus_instance_catalog_item" "vmcreation_vsphere" {
  config          = file("data/vmcreation_vsphere-config.json")
  content         = "Windows Catalog Item :"
  description     = "A catalog item used to deploy a virtual machine on a BEL environment"
  enabled         = true
  featured        = true
#   image_name      = null
#   image_path      = "windows.svg"
  labels                   = ["vmcreation", "terraform_managed"]
  name            = "Windows 2k19 Office on vmware"
  option_type_ids = [2036,2037,2040]
  visibility      = "public"
}
```

ids [2036,2037,2040] corresponding to the same option lists, it appears in the ui and it works, but i don't understand how to get them programaticaly

regards,

JG

**Comment by martezr** [comment]
The resource references used in your example are option lists and not option types which is what the catalog item resource is expecting. You would reference the option type that is mapped to the option list instead of the option list. The provider includes the select list (https://registry.terraform.io/providers/gomorpheus/morpheus/latest/docs/resources/select_list_option_type) and typeahead option types (https://registry.terraform.io/providers/gomorpheus/morpheus/latest/docs/resources/typeahead_option_type) which are backed by option lists. You can also use the option type data source to reference an existing option type (https://registry.terraform.io/providers/gomorpheus/morpheus/latest/docs/data-sources/option_type). Additionally, you can use the option list (https://registry.terraform.io/providers/gomorpheus/morpheus/latest/docs/data-sources/option_list) data source if you want to manage the option type but reference an existing option list.

**Comment by martezr** [comment]
@jigeay Feel free to re-open this issue but it looks like correcting the referenced resource will resolve this issue.
